[versions]
agp = "8.8.0"
gson = "2.8.6"
kotlin = "1.9.10"
appcompat = "1.1.0"
coreKtx = "1.2.0"
junit = "4.12"
junitVersion = "1.2.1"
lifecycleRuntimeKtx = "2.7.0"
material = "1.1.0"
activity = "1.10.1"
constraintlayout = "1.1.3"
coreTesting = "2.1.0"
mockitoCore = "2.27.0"
mockitoKotlin = "2.1.0"
retrofit = "2.7.1"
okhttp = "4.3.1"
picasso = "2.71828"
circleImageView = "3.0.0"
testRunner = "1.1.1"
espresso = "3.1.1"
coroutines = "1.3.3"
coreKtxTest = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleImageView" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtxTest" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
